import keymirror from 'keymirror';

export default keymirror({
  SIGNUP: null,
  LOGIN: null,
  LOGIN_SUCCESSFUL: null,
  SIGNUP_SUCCESSFUL: null,
  DOCUMENT_CREATED: null,
  DOCUMENT_UPDATED: null,
  ALL_DOCUMENTS: null,
  DOCUMENT_UPDATE_FAILED: null,
  VIEW_DOCUMENT: null,
  DOCUMENT_DELETED: null,
  PAGINATED_DOCUMENTS: null,
  SEARCH_DOCUMENTS: null,
  CLEAR_ALL: null,
  PAGINATED_USERS: null,
  USER_UPDATED: null,
  FIND_USER: null,
  USER_DELETED: null,
  ALL_ROLES: null,
  FIND_ROLE: null,
  ROLE_CREATED: null,
  ROLE_DELETED: null,
  VIEW_ROLE: null,
  VIEW_USER: null,
  UPDATE_USER: null,
  PASSWORD_UPDATED: null,
  RESPONSE_ERROR: null,
  CLEAR_ERROR: null
});
